apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster.clusterpedia.io_clustersyncresources.yaml
- cluster.clusterpedia.io_pediaclusters.yaml
- policy.clusterpedia.io_clusterimportpolicies.yaml
- policy.clusterpedia.io_pediaclusterlifecycles.yaml
