apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterpedia_binding_apiserver_apiservice.yaml
- clusterpedia_binding_apiserver_deployment.yaml
- clusterpedia_binding_apiserver_rbac.yaml
